export const Items = [
  {
    category: "Dresses",
    price: 200,
    name: "Rib Dress",
    images: [
      "https://pa.namshicdn.com/product/A8/679631W/2-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A8/679631W/1-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A8/679631W/3-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A8/679631W/5-zoom-desktop.webp",
    ],
    desc: "Round neck with broad shoulder sleeves. Single side slit to hem",
    new: false,
    discount: 185,
    stock: 33,
    bestseller: false,
    short: "Long dress",
  },
  {
    category: "Dresses",
    price: 135,
    name: "Nsw fleece dress",
    images: [
      "https://pa.namshicdn.com/product/A6/342421W/v1/1-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A6/342421W/v1/2-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A6/342421W/v1/6-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A6/342421W/v1/4-zoom-desktop.webp",
    ],
    desc: "Round neck with long sleeves side slit to hem in color brown",
    new: true,
    discount: 100,
    stock: 12,
    bestseller: true,
    short: "Brown fleece dress",
  },
  {
    category: "Dresses",
    price: 100,
    name: "Ginger printed dress",
    images: [
      "https://pa.namshicdn.com/product/A8/975141W/1-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A8/975141W/2-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A8/975141W/3-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A8/975141W/4-zoom-desktop.webp",
    ],
    desc: "soft polyester fabric with adjustable waist belt and short ruffled sleeves",
    new: false,
    discount: 85,
    stock: 9,
    bestseller: false,
    short: "Long printed dress",
  },
  {
    category: "Dresses",
    price: 176,
    name: "Printed V neck",
    images: [
      "https://pa.namshicdn.com/product/A7/979041W/4-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A7/979041W/1-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A7/979041W/2-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A7/979041W/3-zoom-desktop.webp",
    ],
    desc: "Flowy polyester fabric with floral print and elasticated sleeve cuffs",
    new: true,
    discount: 150,
    stock: 20,
    bestseller: true,
    short: "Frilled floral dress",
  },
  {
    category: "Dresses",
    price: 89,
    name: "Printed Tiered Dress",
    images: [
      "https://pa.namshicdn.com/product/A6/310241W/1-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A6/310241W/2-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A6/310241W/3-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A6/310241W/4-zoom-desktop.webp",
    ],
    desc: "Lightweight V-neck dress with patterns and button top closure.",
    new: false,
    discount: 50,
    stock: 25,
    bestseller: true,
    short: "Patterned dress",
  },
  {
    category: "Shirt and Top",
    price: 55,
    name: "Tie-Up Woven Top",
    images: [
      "https://media.6media.me/media/catalog/product/n/5/n50344358v_1.jpg",
      "https://media.6media.me/media/catalog/product/n/5/n50344358v_2.jpg",
      "https://media.6media.me/media/catalog/product/n/5/n50344358v_3.jpg",
      "https://media.6media.me/media/catalog/product/n/5/n50344358v_4.jpg",
    ],
    desc: "Casual long sleeve square neck top in green",
    new: true,
    discount: 40,
    stock: 19,
    bestseller: false,
    short: "Casual top",
  },
  {
    category: "Shirt and Top",
    price: 108,
    name: "Pocket Detail Checked Shirt",
    images: [
      "https://pa.namshicdn.com/product/QF/CJP98801DC/3-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/QF/CJP98801DC/1-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/QF/CJP98801DC/2-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/QF/CJP98801DC/5-zoom-desktop.webp",
    ],
    desc: "Button up checked shirt with front pockets in burgundy",
    new: false,
    discount: 99,
    stock: 12,
    bestseller: false,
    short: "Button up shirt",
  },
  {
    category: "Shirt and Top",
    price: 99,
    name: "Round neck blouse",
    images: [
      "https://pa.namshicdn.com/product/A5/182141W/3-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A5/182141W/1-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A5/182141W/2-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A5/182141W/4-zoom-desktop.webp",
    ],
    desc: "Textured and comfortable fabric with velvet-feel floral patterns.",
    new: false,
    discount: 87,
    stock: 18,
    bestseller: true,
    short: "floral blouse",
  },
  {
    category: "Shirt and Top",
    price: 100,
    name: "Mesh sleeve tunic",
    images: [
      "https://pa.namshicdn.com/product/A8/562711W/1-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A8/562711W/2-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A8/562711W/3-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A8/562711W/4-zoom-desktop.webp",
    ],
    desc: "Sheer polyester fabric with lining and buttoned cuffs on balloon sleeves",
    new: false,
    discount: 89,
    stock: 32,
    bestseller: false,
    short: "Balloon sleeve tunic",
  },
  {
    category: "Sweater and Cardigans",
    price: 143,
    name: "Longline pocket cardigan",
    images: [
      "https://pa.namshicdn.com/product/5T/Q7W38801DC/3-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/5T/Q7W38801DC/1-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/5T/Q7W38801DC/2-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/5T/Q7W38801DC/5-zoom-desktop.webp",
    ],
    desc: "Black knee length cardigan with center strap",
    new: false,
    discount: 125,
    stock: 16,
    bestseller: false,
    short: "Knee length cardigan",
  },
  {
    category: "Sweater and Cardigans",
    price: 120,
    name: "Crew Neck Sweater",
    images: [
      "https://pa.namshicdn.com/product/LS/UR6L8801DC/v2/1-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/LS/UR6L8801DC/v2/2-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/LS/UR6L8801DC/v2/3-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/LS/UR6L8801DC/v2/5-zoom-desktop.webp",
    ],
    desc: "Green and black knitted sweater with buttons and long sleeves",
    new: false,
    discount: 108,
    stock: 34,
    bestseller: true,
    short: "Knitted sweater",
  },
  {
    category: "Sweater and Cardigans",
    price: 143,
    name: "Buttoned Knitted Sweater",
    images: [
      "https://pa.namshicdn.com/product/KN/33J98801DC/1-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/KN/33J98801DC/2-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/KN/33J98801DC/3-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/KN/33J98801DC/4-zoom-desktop.webp",
    ],
    desc: "Yellow knitted sweater with long sleeves",
    new: false,
    discount: 125,
    stock: 45,
    bestseller: true,
    short: "Knitted sweater",
  },
  {
    category: "Sweater and Cardigans",
    price: 109,
    name: "High Neck Sweater",
    images: [
      "https://pa.namshicdn.com/product/ZV/SL358801DC/1-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/ZV/SL358801DC/2-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/ZV/SL358801DC/3-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/ZV/SL358801DC/5-zoom-desktop.webp",
    ],
    desc: "flower printed long sleeve sweater in white",
    new: false,
    discount: 89,
    stock: 33,
    bestseller: false,
    short: "Printed sweater",
  },
  {
    category: "Outwears",
    price: 288,
    name: "Button Down Coat",
    images: [
      "https://pa.namshicdn.com/product/EV/YVW78801DC/v1/1-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/EV/YVW78801DC/v1/2-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/EV/YVW78801DC/v1/3-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/EV/YVW78801DC/v1/4-zoom-desktop.webp",
    ],
    desc: "Knee length green coat with middle strap and buttons",
    new: false,
    discount: 250,
    stock: 15,
    bestseller: false,
    short: "Long coat",
  },
  {
    category: "Outwears",
    price: 315,
    name: "Tailored Knitted Blazer",
    images: [
      "https://pa.namshicdn.com/product/A9/764621W/1-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A9/764621W/2-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A9/764621W/3-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A9/764621W/4-zoom-desktop.webp",
    ],
    desc: "Soft and comfortable polyester fabric with collar neck and front button closure",
    new: false,
    discount: 295,
    stock: 25,
    bestseller: false,
    short: "Knitted blazer",
  },
  {
    category: "Outwears",
    price: 200,
    name: "Cardi B Woven Jacket",
    images: [
      "https://pa.namshicdn.com/product/A1/56239W/1-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A1/56239W/2-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A1/56239W/3-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A1/56239W/5-zoom-desktop.webp",
    ],
    desc: "Soft and comfortable fabric with concealed zipper closure and dual slip-in pockets",
    new: false,
    discount: 185,
    stock: 33,
    bestseller: true,
    short: "Woven jacket",
  },
  {
    category: "Outwears",
    price: 130,
    name: "Buttoned Denim Jacket",
    images: [
      "https://pa.namshicdn.com/product/A6/060431W/1-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A6/060431W/2-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A6/060431W/3-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A6/060431W/4-zoom-desktop.webp",
    ],
    desc: "textured denim fabric with single flap over front pockets and long sleeves",
    new: true,
    discount: 110,
    stock: 18,
    bestseller: true,
    short: "Denim Jacket",
  },
  {
    category: "Outwears",
    price: 120,
    name: "Puff Sleeve Jacket",
    images: [
      "https://pa.namshicdn.com/product/A7/343021W/1-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A7/343021W/2-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A7/343021W/3-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A7/343021W/4-zoom-desktop.webp",
    ],
    desc: "Lightweight polyester scuba fabric with puff shoulders on long sleeves",
    new: false,
    discount: 99,
    stock: 24,
    bestseller: false,
    short: "Polyester jacket",
  },
  {
    category: "Outwears",
    price: 120,
    name: "Checkered Coat",
    images: [
      "https://pa.namshicdn.com/product/A7/513311W/1-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A7/513311W/2-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A7/513311W/3-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A7/513311W/4-zoom-desktop.webp",
    ],
    desc: "Contrast checkered prints over polyester fabric and long sleeves",
    new: false,
    discount: 99,
    stock: 26,
    bestseller: false,
    short: "Printed coat",
  },
  {
    category: "Bags",
    price: 570,
    name: "Flap Over Crossbody",
    images: [
      "https://pa.namshicdn.com/product/A9/665031W/1-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A9/665031W/2-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A9/665031W/3-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A9/665031W/4-zoom-desktop.webp",
    ],
    desc: "Textured and quilted faux leather upper with Embellished with gold-tone studs",
    new: true,
    discount: 500,
    stock: 45,
    bestseller: false,
    short: "Crossbody bag",
  },
  {
    category: "Bags",
    price: 100,
    name: "Faux Leather Backpack",
    images: [
      "https://pa.namshicdn.com/product/12/0KEAD400PM/v7/1-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/12/7LEAD400PM/v10/2-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/12/7LEAD400PM/v10/3-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/12/7LEAD400PM/v10/5-zoom-desktop.webp",
    ],
    desc: "Faux Leather Printed Big Backpack beige",
    new: false,
    discount: 85,
    stock: 67,
    bestseller: false,
    short: "Large backpack",
  },
  {
    category: "Bags",
    price: 465,
    name: "Abey Crossbody",
    images: [
      "https://pa.namshicdn.com/product/A1/265031W/1-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A1/265031W/2-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A1/265031W/3-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A1/265031W/4-zoom-desktop.webp",
    ],
    desc: "Textured and quilted faux leather upper with Flap over construct with inner zipper slot",
    new: false,
    discount: 400,
    stock: 48,
    bestseller: true,
    short: "Crossbody bag",
  },
  {
    category: "Bags",
    price: 112,
    name: "Minimal Bucket Bag",
    images: [
      "https://pa.namshicdn.com/product/A9/937931W/1-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A9/937931W/2-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A9/937931W/3-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A9/937931W/4-zoom-desktop.webp",
    ],
    desc: "Smooth and durable PU upper with Secure inner pouch with zipper closure",
    new: false,
    discount: 95,
    stock: 30,
    bestseller: true,
    short: "Tote bag",
  },
  {
    category: "Shoes",
    price: 299,
    name: "Vista Sandal",
    images: [
      "https://pa.namshicdn.com/product/A5/851031W/1-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A5/851031W/2-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A5/851031W/3-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A5/851031W/4-zoom-desktop.webp",
    ],
    desc: "Textured and durable textile upper with Dual hook-and-loop straps with velcro closure",
    new: false,
    discount: 250,
    stock: 54,
    bestseller: false,
    short: "Durable sandals",
  },
  {
    category: "Shoes",
    price: 188,
    name: "Batman Licenced Shoes",
    images: [
      "https://pa.namshicdn.com/product/15/1D5CJ400PM/v8/1-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/15/1D5CJ400PM/v8/2-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/15/1D5CJ400PM/v8/3-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/15/1D5CJ400PM/v8/4-zoom-desktop.webp",
    ],
    desc: "Woman Batman Licenced Shoes beige",
    new: false,
    discount: 150,
    stock: 76,
    bestseller: false,
    short: "Beige shoes",
  },
  {
    category: "Shoes",
    price: 140,
    name: "Closed Toe Sandals",
    images: [
      "https://pa.namshicdn.com/product/A7/79446W/1-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A7/79446W/2-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A7/79446W/3-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A7/79446W/4-zoom-desktop.webp",
    ],
    desc: "Durable and textured synthetic upper. Slightly cushioned footbed for added comfort",
    new: false,
    discount: 115,
    stock: 15,
    bestseller: false,
    short: "Wedge sandals",
  },
  {
    category: "Shoes",
    price: 109,
    name: "Square Toe Sandal",
    images: [
      "https://pa.namshicdn.com/product/A0/885231W/1-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A0/885231W/2-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A0/885231W/3-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A0/885231W/4-zoom-desktop.webp",
    ],
    desc: "Smooth and durable PU upper. Square tip with slip-on style",
    new: true,
    discount: 99,
    stock: 25,
    bestseller: false,
    short: "Marble print sandals",
  },
  {
    category: "Shoes",
    price: 139,
    name: "Espadrille Sandals",
    images: [
      "https://pa.namshicdn.com/product/A8/79446W/1-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A8/79446W/2-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A8/79446W/3-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A8/79446W/4-zoom-desktop.webp",
    ],
    desc: "Metallic look textured synthetic upper. Slightly cushioned footbed for added comfort",
    new: false,
    discount: 100,
    stock: 45,
    bestseller: false,
    short: "Wedge sandals",
  },
  {
    category: "Shoes",
    price: 116,
    name: "Knotted Strap Slip-On",
    images: [
      "https://pa.namshicdn.com/product/A3/195231W/1-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A3/195231W/2-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A3/195231W/3-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A3/195231W/4-zoom-desktop.webp",
    ],
    desc: "Smooth and durable PU upper. Pointed tip with slip-on style",
    new: true,
    discount: 99,
    stock: 34,
    bestseller: false,
    short: "Stiletto pumps",
  },
  {
    category: "Accessories",
    price: 729,
    name: "Soho Watch+Bracelet",
    images: [
      "https://pa.namshicdn.com/product/A4/659821W/v4/1-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A4/659821W/v4/2-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A4/659821W/v4/3-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A4/659821W/v4/4-zoom-desktop.webp",
    ],
    desc: "Round dial set on stainless steel case. Triple arm movement with marked hourly indices",
    new: false,
    discount: 685,
    stock: 25,
    bestseller: false,
    short: "Stainless steel watch",
  },
  {
    category: "Accessories",
    price: 682,
    name: "Victoriaa Watch",
    images: [
      "https://pa.namshicdn.com/product/A2/064531W/1-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A2/064531W/2-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A2/064531W/3-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A2/064531W/5-zoom-desktop.webp",
    ],
    desc: "Durable linked stainless steel bracelet. Round dial set on stainless steel case",
    new: false,
    discount: 600,
    stock: 15,
    bestseller: true,
    short: "Analogue watch",
  },
  {
    category: "Accessories",
    price: 155,
    name: "Charm Bracelet",
    images: [
      "https://pa.namshicdn.com/product/A8/69727W/1-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A8/69727W/2-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A8/69727W/3-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A8/69727W/4-zoom-desktop.webp",
    ],
    desc: "Dual layered stainless steel bracelet. Logo charm detail with Swarovski crystal",
    new: false,
    discount: 100,
    stock: 65,
    bestseller: false,
    short: "Stainless steel bracelet",
  },
  {
    category: "Accessories",
    price: 436,
    name: "Oval Shape Sunglasses",
    images: [
      "https://pa.namshicdn.com/product/A5/317041W/v3/1-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A5/317041W/v3/2-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A5/317041W/v3/3-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A5/317041W/v3/4-zoom-desktop.webp",
    ],
    desc: "Durable and lightweight acetate frame. Moulded nose pads for comfortable fit",
    new: true,
    discount: 400,
    stock: 43,
    bestseller: false,
    short: "Oval sunglasses",
  },
  {
    category: "Accessories",
    price: 155,
    name: "Central Butterfly Bracelet",
    images: [
      "https://pa.namshicdn.com/product/A7/98579W/1-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A7/98579W/2-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A7/98579W/3-zoom-desktop.webp",
      "https://pa.namshicdn.com/product/A8/98579W/1-zoom-desktop.webp",
    ],
    desc: "Smooth, linked silver-toned bracelet. Butterfly charm with Swarovski crystals",
    new: false,
    discount: 105,
    stock: 30,
    bestseller: false,
    short: "Silver-toned bracelet",
  },
];
